const axios = require("axios");
const FormData = require("form-data");
const fs = require("fs");
const sharp = require("sharp");

async function detectImage(imagePath) {
  try {
    console.log("Image received for detection:", imagePath);

    // ==========================================
    // STEP 1: Normalize image
    // ==========================================

    const processedImagePath = `${imagePath}-processed.jpg`;

    await sharp(imagePath)
      .rotate()
      .resize({
        width: 2000,
        height: 2000,
        fit: "inside",
        withoutEnlargement: true,
      })
      .jpeg({
        quality: 90,
      })
      .toFile(processedImagePath);

    console.log("Image processed successfully.");

    // ==========================================
    // STEP 2: Create FormData
    // ==========================================

    const formData = new FormData();

    formData.append(
      "media",
      fs.createReadStream(processedImagePath)
    );

    formData.append("models", "genai");

    formData.append(
      "api_user",
      process.env.SIGHTENGINE_API_USER
    );

    formData.append(
      "api_secret",
      process.env.SIGHTENGINE_API_SECRET
    );

    // ==========================================
    // STEP 3: Send image to Sightengine
    // ==========================================

    const response = await axios.post(
      "https://api.sightengine.com/1.0/check.json",
      formData,
      {
        headers: {
          ...formData.getHeaders(),
        },
      }
    );

    console.log(
      "Sightengine Response:",
      JSON.stringify(response.data, null, 2)
    );

    // ==========================================
    // STEP 4: Get AI probability
    // ==========================================

    const aiProbability =
      response.data?.type?.ai_generated;

    if (typeof aiProbability !== "number") {
      throw new Error(
        "AI detection score was not returned by Sightengine."
      );
    }

    const aiPercentage = Number(
      (aiProbability * 100).toFixed(1)
    );

    const realPercentage = Number(
      ((1 - aiProbability) * 100).toFixed(1)
    );

    console.log(
      "AI Probability:",
      aiPercentage + "%"
    );

    console.log(
      "Real Probability:",
      realPercentage + "%"
    );

    // ==========================================
    // STEP 5: Decide verdict
    // ==========================================

    let verdict;
    let confidence;
    let reason;

    // HIGH AI probability
    if (aiProbability >= 0.7) {
      verdict = "ai_generated";

      confidence = aiPercentage;

      reason =
        "The image shows a high probability of being generated or significantly modified using generative AI.";
    }

    // LOW AI probability
    else if (aiProbability <= 0.3) {
      verdict = "real";

      confidence = realPercentage;

      reason =
        "The image shows a low probability of being generated by generative AI and is likely a real image.";
    }

    // INCONCLUSIVE
    else {
      verdict = "uncertain";

      // Distance from the uncertain midpoint.
      // This prevents misleading high confidence.
      confidence = Number(
        (Math.max(aiProbability, 1 - aiProbability) * 100).toFixed(1)
      );

      reason =
        "The AI detection score is inconclusive. The image cannot be confidently classified as real or AI generated.";
    }

    console.log("Final Verdict:", verdict);
    console.log("Confidence:", confidence + "%");

    // ==========================================
    // STEP 6: Detection indicators
    // ==========================================

    const indicators = [
      {
        name: "AI Generated Probability",
        value: `${aiPercentage}%`,
      },
      {
        name: "Likely Real Probability",
        value: `${realPercentage}%`,
      },
    ];

    // ==========================================
    // STEP 7: Cleanup
    // ==========================================

    try {
      if (fs.existsSync(processedImagePath)) {
        fs.unlinkSync(processedImagePath);
      }

      if (fs.existsSync(imagePath)) {
        fs.unlinkSync(imagePath);
      }
    } catch (cleanupError) {
      console.log(
        "Temporary file cleanup warning:",
        cleanupError.message
      );
    }

    // ==========================================
    // FINAL RESULT
    // ==========================================

    return {
      verdict,
      confidence,
      reason,
      aiProbability: aiPercentage,
      realProbability: realPercentage,
      indicators,
    };

  } catch (error) {
    console.error(
      "Image Detection Error:",
      error.response?.data || error.message
    );

    throw new Error(
      error.response?.data?.error?.message ||
        error.message ||
        "Unable to analyze image."
    );
  }
}

module.exports = {
  detectImage,
};